Arbre decision api part
betagouv/api.gouv.fr pull request #1078
Opened 2022-10-27 09:36 UTC by SchweisguthN

Ajout des modèles pré-remplis Datapass à la page "Demande accès" d'API Part

2022-10-27 09:46 UTC, XavierJp requested changes

2022-10-27 09:46 UTC, XavierJp commented on components/questionTree/data/api-particulier/index.ts
> +    question: 'Qui sera en charge techniquement de l’intégration de l’API Particulier ?',
Bravo, beau verbe ! 

C'est un peu dommage de ne mettre que le choix elligible. Profitons en pour adresser ceux qui ne sont pas élligible (particulier, entreprise etc. et leur dire déso mais c'est pas pour vous)

2022-10-27 09:51 UTC, XavierJp commented on components/questionTree/data/api-particulier/eligible.ts
> +        answer: `Conformément aux dispositions de <External href="https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000031366350&idArticle=LEGIARTI000031367412&dateTexte=&categorie
La section : 

```
Conformément aux dispositions de <External href="https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000031366350&idArticle=LEGIARTI000031367412&dateTexte=&categorieLien=cid">l'article L114-8</External> du *code des relations entre le public et l'administration*, seules les administrations sont habilitées à échanger entre elles des informations ou données strictement nécessaires pour traiter une démarche.
            <br/><br/>
            Pour obtenir un agrément, vous devez **justifier d'une simplification pour les citoyens**, et vous engager à
            n'accéder aux données personnelles qu'avec **l'accord explicite** de l'usager.
            <br/><br/>
```

semble se répéter pour tous les éditeurs. Est ce qu'on pourrait pas trouver un moyen de le mettre en commun et l'écrire une seule fois ?

2022-10-27 13:12 UTC, SchweisguthN commented
@XavierJp J'ai poussé un nouveau commit. C'est un peu sec sans texte quand on a sélectionné l'éditeur, il n'y a pas trop de texte, mais au moins plus de problème de factorisation.

<img width="736" alt="Capture d’écran 2022-10-27 à 15 06 48" src="https://user-images.githubusercontent.com/63580587/198292679-3cdb889b-5c77-40d9-962e-bca43658d64f.png">

2022-11-14 17:54 UTC, XavierJp approved these changes
Tellement belle que je l'approuve direct !

2022-11-16 08:32 UTC, merged