Porpose d'ajouter les liens vers formulaires d'accès au POC Octroi
betagouv/api.gouv.fr pull request #1135
Opened 2023-02-14 09:52 UTC by DorineLam

Modifie l'arbre d'accès de l'API Entreprise pour renvoyer les usagers sans éditeur et sans équipe technique vers les formulaires du POC Octroi

2023-02-14 10:09 UTC, DorineLam commented
@Samuelfaure j'ai ouvert cette PR pour ajouter des liens vers les futurs formulaires d'inscription au POC Octroi. Je ne peux pas voir le rendu en local.
L'idéal serait de pouvoir mettre un composant de type "Mise en avant" [cf DSFR](https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/mise-en-avant/).

2023-02-22 07:49 UTC, DorineLam commented
@Samuelfaure la PR dont je te parlais

2023-02-22 12:34 UTC, Samuelfaure requested changes

2023-02-22 12:34 UTC, Samuelfaure commented on components/questionTree/data/api-entreprise/eligible.ts
> +      <br/>- <External href='TODO'>Demander un accès au site pour les données utiles "marchés publics"</External>.
Fixer ça et on est bon

2023-02-22 13:00 UTC, DorineLam commented on components/questionTree/data/api-entreprise/eligible.ts
> +      <br/>- <External href='TODO'>Demander un accès au site pour les données utiles "marchés publics"</External>.
@Samuelfaure justement, je ne sais pas comment mettre la seconde ligne en commentaire

2023-02-24 10:44 UTC, Samuelfaure commented on components/questionTree/data/api-entreprise/eligible.ts
> +      <br/>- <External href='TODO'>Demander un accès au site pour les données utiles "marchés publics"</External>.
@DorineLam Supprime la dans un nouveau commit au pire, quand on voudra la remettre on aura qu'à revert le commit

2023-02-24 15:37 UTC, DorineLam commented on components/questionTree/data/api-entreprise/eligible.ts
> +      <br/>- <External href='TODO'>Demander un accès au site pour les données utiles "marchés publics"</External>.
C'est fait :)

2023-02-28 08:12 UTC, Samuelfaure approved these changes

2023-02-28 08:42 UTC, merged