Update api_hubeau_onde.md
betagouv/api.gouv.fr pull request #1184
Opened 2023-05-12 15:47 UTC by b-lardeau

Ajout de contenu : Annonce passage vbeta -> v1

2023-05-15 09:48 UTC, Isalafont requested changes

2023-05-15 09:48 UTC, Isalafont commented on _data/api/api_hubeau_onde.md
> +L'API est actuellement en version beta son passage en version 1 est prévu pour le **mardi 23/05/2023** à la mi-journée.
Pourriez vous rajouter ces informations de la nouvelle version ligne 39 au dessus de `- 29/06/2022 : mise à disposition de la version beta ` pour une meilleure lisibilité ?

Par exemple : 

```
Dernières évolutions de l'API Ecoulement des cours d'eau de Hub'Eau:
- 23/05/2023 : Mise à disposition mi-journée de la version 1 en place de la version beta
- 29/06/2022 : mise à disposition de la version beta  
```
En vous remerciant par avance.

2023-05-15 11:45 UTC, b-lardeau commented on _data/api/api_hubeau_onde.md
> +L'API est actuellement en version beta son passage en version 1 est prévu pour le **mardi 23/05/2023** à la mi-journée.
Le fichier a été complété.

Cordialement.

2023-05-22 12:41 UTC, Isalafont approved these changes

2023-05-22 12:41 UTC, Isalafont commented on _data/api/api_hubeau_onde.md
> +L'API est actuellement en version beta son passage en version 1 est prévu pour le **mardi 23/05/2023** à la mi-journée.
Merci beaucoup.

2023-05-22 12:41 UTC, merged

2023-05-23 15:57 UTC, b-lardeau commented on _data/api/api_hubeau_onde.md
> +L'API est actuellement en version beta son passage en version 1 est prévu pour le **mardi 23/05/2023** à la mi-journée.
Bonjour @Isalafont,
La modification semble avoir été mergée vers master hier mais n'apparait pas en ligne sur https://api.gouv.fr/les-api/api_hubeau_onde.
Y -a-t-il un délai de publication/déploiement ?
Merci d'avance pour votre éclairage.

2023-05-24 07:57 UTC, Isalafont commented on _data/api/api_hubeau_onde.md
> +L'API est actuellement en version beta son passage en version 1 est prévu pour le **mardi 23/05/2023** à la mi-journée.
Nous allons lancé un merge en production dans la journée.