replace agentconnect by proconenct
betagouv/api.gouv.fr pull request #1384
Opened 2024-10-02 15:06 UTC by felhix

remplacement de AgentConnect par ProConnect suite au renommage de AgentConnect par ProConnect

2024-10-02 16:10 UTC, SchweisguthN commented on _data/api/agent-connect.md
> +tagline: Le solution officielle qui vous identifie en tant que .
En tant que ?

2024-10-08 07:59 UTC, Isalafont requested changes

2024-10-08 07:59 UTC, Isalafont commented on _data/api/agent-connect.md
> +Utiliser l'API ProCOnnect pour identifier les agents utilisateurs de votre site permet d'accéder à **l'identité pivot**.
Il y a une petit typo ici : ProConnect

2024-10-08 07:59 UTC, Isalafont commented on _data/guides/authentification.md
> +Certaines applications veulent pouvoir identifier des professionnels, que ce soit par exemple pour des démarches, du logiciel bureatique, des accès à des données.
Petit typo également sur le mot bureautique

2024-10-09 08:06 UTC, Isalafont approved these changes

2024-10-09 08:06 UTC, merged