create ANS
betagouv/api.gouv.fr pull request #663
Opened 2021-03-22 17:43 UTC by etienne0101

2021-03-23 08:33 UTC, XavierJp requested changes
Great first Pull Request, a few details here and there but bravo !

2021-03-23 08:33 UTC, XavierJp commented on _data/api/pro-sante-connect.md
> +tagline: Permettre l'authentification des professionnels de la santé
I prefer to use a verb that describe the most frequent use of with this API. Eg. Identifier, Authentifier or Accéder aux données

We can add a mention of RPPS or the id used to identified a "professionnel"

2021-03-23 08:33 UTC, XavierJp commented on _data/api/pro-sante-connect.md
> +datapass_link: https://esante.gouv.fr/
We can leave it empty for now, or comment. To comment, add a # at the beginning of the line

2021-03-23 08:33 UTC, XavierJp commented on _data/api/pro-sante-connect.md
> +      Seuls les éditeurs de logiciels proposant une solution web adressée aux professionnels de santé peuvent demander à se raccorder à PRO Santé Connect.
We miss the condition "french"

Let's choose one spelling for Pro Santé Connect . According to their website I would stick to Pro Santé Connect and avoid PRO

2021-03-23 08:33 UTC, XavierJp commented on _data/api/pro-sante-connect.md
> +      <Button href="https://franceconnect.gouv.fr/partenaires">Remplir une demande</Button>
We can use `href="mailto:prosanteconnect.editeurs@esante.gouv.fr"`

2021-03-23 08:33 UTC, XavierJp commented on _data/api/pro-sante-connect.md
> +
I advise to always have a CTA here

`<NextSteps />
<Button href="mailto:prosanteconnect.editeurs@esante.gouv.fr">Remplir une demande</Button>`

2021-03-23 08:33 UTC, XavierJp commented on _data/api/pro-sante-connect.md
> +      Tout éditeur proposant une solution web adressée aux professionnels de santé et qui souhaite pouvoir authentifier des professionnels de santé peut demander à se raccorder à PRO Santé Connect.
Add french, fix Pro/PRO

2021-03-23 08:33 UTC, XavierJp commented on _data/api/pro-sante-connect.md
> +  - Editeurs
Perfect. I would maybe add `Connect` and `RPPS`, `adeli`, ìdNat`

2021-03-23 08:33 UTC, XavierJp commented on _data/api/pro-sante-connect.md
> +### A quoi ca sert ?
Prefer 
A quoi sert cette API ?

2021-03-23 08:33 UTC, XavierJp commented on _data/api/pro-sante-connect.md
> +### Comment ça marche ?
Prefer 
Données accessibles dans l'API

2021-03-23 08:33 UTC, XavierJp commented on _data/api/pro-sante-connect.md
> +| Données d'identification       | nom, prénom, idNat (Adeli ou RPPS) |
I would split it this way
| Identifiant unique (idNat) | Adeli ou RPPS |
| état civil | nom et prénom |

2021-03-23 10:32 UTC, etienne0101 commented
Thanks @XavierJp for commenting, It should be ok now

2021-05-21 14:30 UTC, XavierJp commented
@etienne0101 je ferme cette vieille PR qui est redondante avec #696

2021-05-21 14:30 UTC, closed without merging