Api entreprise/more questions
betagouv/api.gouv.fr pull request #816
Opened 2021-10-22 13:42 UTC by Samuelfaure

~~⚠️ En draft pour le moment, il me reste quelques détails à voir avec Dorine, mais la review peut déjà être faite.~~

Normalement je travaille en commits atomiques, mais ça a été un peu difficile de faire ça ici, donc je conseille la review en une fois plutôt que commit par commit. Sorry pour ça 😅

2021-11-09 12:18 UTC, Samuelfaure commented
OK on devrait être bon! On fait quelques checks cette aprème (responsive etc) mais ça devrait passer :)

2021-11-09 14:30 UTC, XavierJp requested changes

2021-11-09 14:30 UTC, XavierJp commented on .eslintrc.json
> +    "react/jsx-no-target-blank": [2, {
Je suis toujours un peu perplexe sur la désactivation de la règle pour tout le site. Peut-on à la rigueur envisager de désactiver eslint sur la ligne concernée ? Ou bien juste d'ajouter un `noreferrer noopener`

2021-11-09 14:30 UTC, XavierJp commented on components/questionTree/styles.scss
> +  .result {
J'ai l'impression que `result` n'est plus utilisé non ?

2021-11-09 14:30 UTC, XavierJp commented on components/questionTree/index.tsx
> +const preferMarkdown = (input: string | JSX.Element | undefined) => {
Est ce qu'il y a encore du JSX dans le questionTree ? Sinon on peut se passer de `preferMarkdown` et toujours rendre `<RichReactMarkdown />`

2021-11-09 14:30 UTC, XavierJp commented on components/questionTree/styles.scss
> +  .margin-top {
Pareil je n'ai pas trouvé la classe `margin-top`

2021-11-09 14:30 UTC, XavierJp commented on components/questionTree/styles.scss
> +  .small-margin-bottom {
idem

2021-11-09 14:30 UTC, XavierJp commented on components/questionTree/styles.scss
> +  ul.no-bullets {
idem je ne les trouve pas dans la PR

2021-11-09 14:30 UTC, XavierJp commented on uiComponents/button/buttonCopy.tsx
> +import React from 'react';
Je preferrerais que ButtonCopy soit un composant distinct de button dans `uiComponents/button-copy` mais je peux m'en charger

2021-11-11 13:10 UTC, XavierJp approved these changes

2021-11-11 13:13 UTC, merged