Correction du lien vers l'"API"
betagouv/api.gouv.fr pull request #823
Opened 2021-11-04 19:08 UTC by oncletom

Le bouton "Accéder au site de l’API" devrait pointer vers data.gouv.fr

2021-11-04 21:27 UTC, XavierJp requested changes

2021-11-04 21:27 UTC, XavierJp commented on _data/api/api_cartobio_territoires.md
> +doc_external_link: https://www.data.gouv.fr/fr/datasets/616d6531c2951bbe8bd97771/
hello ! `doc_external_link` est sensé renvoyer vers la doc technique de l'API mais le lien me donne une 404

2021-11-04 21:41 UTC, oncletom commented on _data/api/api_cartobio_territoires.md
> +doc_external_link: https://www.data.gouv.fr/fr/datasets/616d6531c2951bbe8bd97771/
Le jeu de données n'est pas encore publié (dans quelques jours).

Je cherchais à ce que ce bouton renvoie vers "le jeu de données", et non à la page de documentation (https://api.gouv.fr/documentation/api_cartobio_territoires).

<img width="386" alt="image" src="https://user-images.githubusercontent.com/138627/140424047-460469ca-c6c7-409d-84ed-c3d4b9b966cb.png">

2021-11-05 08:45 UTC, XavierJp commented on _data/api/api_cartobio_territoires.md
> +doc_external_link: https://www.data.gouv.fr/fr/datasets/616d6531c2951bbe8bd97771/
Hum alors le bouton Tester l'API renvoie systématiquement vers le swagger si il existe (`doc_tech_link`).

`doc_external_link`, fera apparaitre un bouton secondaire avec écrit "Accéder à la Documentation" comme sur https://api.gouv.fr/les-api/api-entreprise

2021-11-09 12:19 UTC, oncletom commented on _data/api/api_cartobio_territoires.md
> +doc_external_link: https://www.data.gouv.fr/fr/datasets/616d6531c2951bbe8bd97771/
En pratique on souhaite remplacer le lien vers l'accès au DataPass par un lien vers DataGouv.
Je me rends compte que ma modification ne permet pas d'y parvenir.

Comment faire dans ce cas ?

2021-11-09 13:40 UTC, XavierJp commented on _data/api/api_cartobio_territoires.md
> +doc_external_link: https://www.data.gouv.fr/fr/datasets/616d6531c2951bbe8bd97771/
Hello, on a deux cas :
- soit tu as un swagger et dans ce cas renseigne le dans `doc_tech_link` et le bouton affichera 'Tester l’API'
- soit tu n'as pas de swagger mais une doc externe et dans ce ca `doc_tech_external` et le bouton affichera 'Accéder au site de l’API'

Par contre je suis perturbé par le lien vers datagouv. Est ce que cela veut dire que la documentation de l'API est sur datagouv ? Ou est ce que ca veut dire que CartoBio n'est pas une API mais des données plates. Auquel cas on peut envisager de supprimer la page cartoBio sur api.gouv.fr et faire un redirect vers datagouv si c'est plus pertinent.

2021-11-09 17:58 UTC, oncletom commented on _data/api/api_cartobio_territoires.md
> +doc_external_link: https://www.data.gouv.fr/fr/datasets/616d6531c2951bbe8bd97771/
On peut en effet envisager une redirection — on avait fait une page API pour avoir le DataPass, et distribuer des données plates par ce guichet.

2021-11-09 17:58 UTC, closed without merging